services:
  # Insecure API
  - type: web
    name: v1-insecure-api
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && node src/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: v1-insecure-db
          property: connectionString
      - key: PORT
        value: 10000

  # Insecure Frontend
  - type: static
    name: v1-insecure-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: v1-insecure-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: v1-insecure-db
    plan: free
    databaseName: healthcure
    user: postgres
